### PR TITLE
Json file for posts

### PR DESCRIPTION
**Pull request by tmess567**
Posts can be fetched from a json file which is easier to make changes to.
Also, we can add a form to allow authenticated users to add posts.

### CODE REVIEW

**Comment by karandesai-96** [comment]
@tmess567 That's a very beautiful piece of code, and it functions very well. Thanks for this PR ! 
About the form authentication: these devlogs are hosted using **gh-pages** and I'm afraid that **gh-pages** will not allow any backend work (It is static hosting). And anyhow, to allow more people to add posts (say it is a collective devlog of a project maintained by two people), it is as simple as giving push access of my devlog repository to other person. :smile: 

If you think that I misunderstood your point, or you have a some better implementation, I'm listening to you. But as far as this PR is concerned, I'm happy to merge. Please let me know if you have completed your work here.

**Comment by tmess567** [comment]
I understand your point about the static pages (I've been thinking about it all night). An idea that I had was to configure firebase with it. That will allow us to have authentication while providing us with a dynamic database. I haven't worked with io pages or firebase auth, so I have yet to see if it is safe to post firebase private info on a public repo. What do you think about it?

I've also added a footer to my github io page that I customized from this, but I've not yet configured the main tag to stay above the footer. Once the no. Of posts increase, I believe it will start going behind the footer instead of allowing a scroll. I'll work on that when I get the time to. I've also added some media queries to make it responsive. That one's not complete, expect another PR in a couple of days.

**Comment by karandesai-96** [comment]
Great, thanks. Make sure that this integration can be easily ignored by people who want to write posts for short term (maybe 3-4 weeks ?) as they want something that can be set up very quickly, and for people maintaining for a long term, they'll find it useful anyway !

I'll merge this then.

**Comment by karandesai-96** [comment]
I assume you have noticed this, I have used materializecss framework for UI. It provides great components, see if you can ease up your work: http://materializecss.com/

**Pull request merged**
